//types.js
export const GET_PROFILES = 'GET_PROFILES';
export const GET_TABLES = 'GET_TABLES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SELECTED_PRODUCTS = 'SELECTED_PRODUCTS';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const PROFILE_SESSION = 'PROFILE_SESSION';
